# Generated by Django 2.2.7 on 2019-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
